### ISSUE TITLE
Nefunkční některé části

### ISSUE THREAD

**Issue by pruchadev** [bakalaborg/bakalab#2]
Ahoj,
včera jsem si nainstaloval Vaší aplikaci a nefungují mi některé části, pouze se načítají, ale nakonec se nic nenačte.

Domů - zde se nenačte nic
Známky
Absence

Pro upřesnění mám Android 8.0 a telefon Huawei P20 Lite a testuji vše na https://bakalari.copsu.cz

**Comment by vojta-horanek** [comment]
Ahoj, to je naprosto v pořádku, domů ještě není plně implementováno (pouze placeholder). Známky jsou opraveny v nejnovějším commitu (ještě není vygenerováno apk) a absence není hotová tudíž je tam taky jako placeholder (momentálně stejně jako známky podle předmětů)

**Comment by pruchadev** [comment]
Ok, ale i tak dobrá práce.
